from __future__ import annotations

INITIAL_CONTACTS = [
    {
        "id": "pegognaga-comune-centralino",
        "nome": "Comune di Pegognaga - Centralino",
        "categoria": "Comune",
        "telefono": "03765546211",
        "email": "protocollo@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Contatto generale del Comune.",
        "tags": ["comune", "centralino", "protocollo"],
        "fonte": "Comune di Pegognaga - Homepage",
    },
    {
        "id": "pegognaga-segreteria-protocollo",
        "nome": "Comune di Pegognaga - Segreteria e Protocollo",
        "categoria": "Protocollo",
        "telefono": "03765546206 / 03765546228",
        "email": "protocollo@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "orari": "Ricevimento su prenotazione secondo orari pubblicati dal Comune.",
        "note": "Ufficio per protocollo documenti, pratiche e corrispondenza ufficiale.",
        "tags": ["protocollo", "segreteria", "atti", "comune"],
        "fonte": "Comune di Pegognaga - Ufficio Segreteria e Protocollo",
    },
    {
        "id": "pegognaga-polizia-locale",
        "nome": "Comune di Pegognaga - Polizia Locale",
        "categoria": "Polizia Locale",
        "telefono": "03765546216",
        "email": "vigili@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "orari": "Lunedi 09:30-13:00 accesso libero; mercoledi 09:30-13:00 su prenotazione; venerdi 09:30-13:00 accesso libero.",
        "note": "Polizia Stradale, Polizia Giudiziaria, Polizia Amministrativa, controllo territorio, permessi invalidi, permessi rosa, Codice della Strada.",
        "tags": ["polizia locale", "cds", "permessi invalidi", "controllo territorio"],
        "fonte": "Comune di Pegognaga - Ufficio Polizia Locale",
    },
    {
        "id": "pegognaga-ambiente-urbanistica",
        "nome": "Comune di Pegognaga - Ambiente e Urbanistica",
        "categoria": "Ufficio tecnico",
        "telefono": "03765546223",
        "email": "esecchi@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Pratiche ambientali e pianificazione territoriale.",
        "tags": ["ambiente", "urbanistica", "territorio"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-edilizia-privata",
        "nome": "Comune di Pegognaga - Edilizia Privata",
        "categoria": "Ufficio tecnico",
        "telefono": "03765546222",
        "email": "dbertolini@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Pratiche edilizie presentate al SUE da privati e imprese.",
        "tags": ["edilizia", "sue", "urbanistica"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-lavori-pubblici",
        "nome": "Comune di Pegognaga - Lavori Pubblici",
        "categoria": "Ufficio tecnico",
        "telefono": "03765546220",
        "email": "jbenatti@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "orari": "Lunedi, mercoledi e venerdi 09:30-13:00 su prenotazione secondo pagina comunale.",
        "note": "Opere pubbliche, protezione civile, piano di protezione civile, abusi edilizi, vigilanza urbanistico-edilizia.",
        "tags": ["lavori pubblici", "protezione civile", "abusi edilizi", "segnalazioni"],
        "fonte": "Comune di Pegognaga - Ufficio Lavori Pubblici",
    },
    {
        "id": "pegognaga-manutenzioni",
        "nome": "Comune di Pegognaga - Manutenzioni",
        "categoria": "Segnalazioni e manutenzioni",
        "telefono": "03765546304",
        "email": "amanfredini@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "orari": "Lunedi, mercoledi e venerdi 09:30-13:00 su prenotazione secondo pagina comunale.",
        "note": "Gestione segnalazioni, manutenzioni territorio, sfalci, caditoie, neve, idoneita alloggiativa, sale civiche.",
        "tags": ["manutenzioni", "segnalazioni", "caditoie", "neve", "sfalci", "idoneita alloggiativa"],
        "fonte": "Comune di Pegognaga - Ufficio Manutenzioni",
    },
    {
        "id": "pegognaga-anagrafe-stato-civile-leva",
        "nome": "Comune di Pegognaga - Anagrafe, Stato Civile, Leva",
        "categoria": "Comune",
        "telefono": "03765546240 / 03765546218",
        "email": "dborgonovi@comune.pegognaga.mn.it; gsimeoni@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Anagrafe, stato civile, leva, residenza, nascita, matrimonio, morte.",
        "tags": ["anagrafe", "stato civile", "leva", "residenza"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-elettorale",
        "nome": "Comune di Pegognaga - Elettorale",
        "categoria": "Comune",
        "telefono": "03765546202",
        "email": "gbattesini@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Liste elettorali e procedimenti elettorali.",
        "tags": ["elettorale", "elezioni"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-commercio-eventi",
        "nome": "Comune di Pegognaga - Commercio ed Eventi",
        "categoria": "Comune",
        "telefono": "03765546244",
        "email": "szambelli@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Attivita, eventi, autorizzazioni e concessioni.",
        "tags": ["commercio", "eventi", "autorizzazioni"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-comunicazione-innovazione",
        "nome": "Comune di Pegognaga - Comunicazione e Innovazione P.A.",
        "categoria": "Comune",
        "telefono": "03765546243",
        "email": "acapelli@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Comunicazione istituzionale e innovazione.",
        "tags": ["comunicazione", "innovazione", "pa"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-segretario-comunale",
        "nome": "Comune di Pegognaga - Segretario Comunale",
        "categoria": "Comune",
        "telefono": "03765546206",
        "email": "segretario@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Assistenza giuridico-amministrativa dell'ente.",
        "tags": ["segretario", "atti", "amministrativo"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-gestione-entrate",
        "nome": "Comune di Pegognaga - Gestione Entrate",
        "categoria": "Tributi",
        "telefono": "03765546205",
        "email": "eallari@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Entrate tributarie ed extratributarie.",
        "tags": ["entrate", "tributi"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-gestione-spesa",
        "nome": "Comune di Pegognaga - Gestione Spesa",
        "categoria": "Comune",
        "telefono": "03765546233",
        "email": "epasserini@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Liquidazioni e pagamenti.",
        "tags": ["spesa", "pagamenti", "ragioneria"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-patrimonio",
        "nome": "Comune di Pegognaga - Patrimonio",
        "categoria": "Ufficio tecnico",
        "telefono": "03765546201",
        "email": "fbardoscia@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Manutenzione immobili comunali e patrimonio.",
        "tags": ["patrimonio", "immobili", "manutenzione"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-personale",
        "nome": "Comune di Pegognaga - Personale",
        "categoria": "Comune",
        "telefono": "03765546225",
        "email": "stonelli@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Gestione del personale dipendente.",
        "tags": ["personale", "dipendenti"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-servizi-sociali-scuola",
        "nome": "Comune di Pegognaga - Servizi Sociali, Scuola, Nido e Trasporti Sociali",
        "categoria": "Servizi sociali",
        "telefono": "03765546301",
        "email": "cpoltronieri@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "note": "Servizi scolastici, nido, trasporto sociale e collaborazione con assistenti sociali.",
        "tags": ["servizi sociali", "scuola", "nido", "trasporto sociale"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "pegognaga-tributi",
        "nome": "Comune di Pegognaga - Tributi",
        "categoria": "Tributi",
        "telefono": "03765546226",
        "email": "tributi@comune.pegognaga.mn.it",
        "pec": "pegognaga.mn@legalmail.it",
        "indirizzo": "Piazza Giacomo Matteotti, 1 - 46020 Pegognaga (MN)",
        "orari": "Lunedi, mercoledi e venerdi 09:30-13:00 su prenotazione secondo pagina comunale.",
        "note": "Tributi comunali, IMU, accertamenti, riscossione, rimborsi.",
        "tags": ["tributi", "imu", "riscossione"],
        "fonte": "Comune di Pegognaga - Ufficio Tributi",
    },
    {
        "id": "pegognaga-centro-culturale",
        "nome": "Comune di Pegognaga - Centro Culturale",
        "categoria": "Comune",
        "telefono": "03765546401",
        "email": "centro@centroculturalepegognaga.it",
        "indirizzo": "Pegognaga (MN)",
        "note": "Centro Culturale Livia Bottardi Milani.",
        "tags": ["centro culturale", "biblioteca", "cultura"],
        "fonte": "Comune di Pegognaga - Uffici telefono e posta elettronica",
    },
    {
        "id": "nue-112",
        "nome": "Numero Unico Emergenza 112",
        "categoria": "Emergenza",
        "telefono": "112",
        "note": "Numero unico per tutte le emergenze in Lombardia. Attivo 24 ore su 24, gratuito da fisso e mobile. Smista verso soccorso sanitario, Forze di Polizia e Vigili del Fuoco.",
        "tags": ["emergenza", "112", "soccorso", "nue"],
        "fonte": "AREU Lombardia / Regione Lombardia",
    },
    {
        "id": "continuita-assistenziale-116117",
        "nome": "Continuita Assistenziale ex Guardia Medica",
        "categoria": "Sanità",
        "telefono": "116117",
        "note": "Numero unico gratuito per continuita assistenziale/ex Guardia Medica in Lombardia. Non sostituisce il 112 per emergenze-urgenze.",
        "tags": ["guardia medica", "continuita assistenziale", "sanita"],
        "fonte": "ATS Val Padana / ASST Mantova",
    },
    {
        "id": "carabinieri-pegognaga",
        "nome": "Carabinieri - Stazione di Pegognaga",
        "categoria": "Forze di Polizia",
        "telefono": "0376558034",
        "email": "stmn12a240@carabinieri.it",
        "pec": "tmn21161@pec.carabinieri.it",
        "indirizzo": "Strada Chiaviche 17/B - 46020 Pegognaga (MN)",
        "note": "Stazione Carabinieri territoriale.",
        "tags": ["carabinieri", "forze di polizia", "pegognaga"],
        "fonte": "Comune di Pegognaga / IPA",
    },
    {
        "id": "vigilfuoco-mantova",
        "nome": "Vigili del Fuoco - Comando Provinciale Mantova",
        "categoria": "Vigili del Fuoco",
        "telefono": "037622771",
        "email": "comando.mantova@vigilfuoco.it",
        "pec": "com.mantova@cert.vigilfuoco.it",
        "indirizzo": "Viale Risorgimento, 16 - 46100 Mantova (MN)",
        "note": "Per emergenze usare 112. Contatto amministrativo/centralino Comando provinciale.",
        "tags": ["vigili del fuoco", "mantova", "soccorso", "prevenzione incendi"],
        "fonte": "Corpo Nazionale Vigili del Fuoco - Comando Mantova",
    },
    {
        "id": "prefettura-mantova",
        "nome": "Prefettura - U.T.G. di Mantova",
        "categoria": "Prefettura",
        "telefono": "03762351",
        "pec": "protocollo.prefmn@pec.interno.it",
        "indirizzo": "Via Principe Amedeo, 30 - 46100 Mantova (MN)",
        "note": "Prefettura/Ufficio Territoriale del Governo di Mantova.",
        "tags": ["prefettura", "utg", "mantova"],
        "fonte": "Prefettura di Mantova",
    },
    {
        "id": "questura-mantova",
        "nome": "Questura di Mantova",
        "categoria": "Questura",
        "telefono": "03762051",
        "pec": "gab.quest.mn@pecps.poliziadistato.it",
        "indirizzo": "Piazza Sordello, 46 - 46100 Mantova (MN)",
        "note": "Contatto generale Questura. Verificare PEC specifiche per ufficio prima dell'invio di pratiche particolari.",
        "tags": ["questura", "polizia di stato", "mantova"],
        "fonte": "Polizia di Stato / IPA",
    },
    {
        "id": "provincia-mantova-urp",
        "nome": "Provincia di Mantova - URP/Centralino",
        "categoria": "Provincia",
        "telefono": "03762041 / 0376204741",
        "email": "urp@provincia.mantova.it",
        "pec": "provinciadimantova@legalmail.it",
        "indirizzo": "Mantova (MN)",
        "note": "Contatti generali Provincia di Mantova.",
        "tags": ["provincia", "urp", "mantova"],
        "fonte": "Provincia di Mantova",
    },
    {
        "id": "mantova-ambiente-tea-numero-verde",
        "nome": "Mantova Ambiente / Tea - Numero Verde",
        "categoria": "Ambiente e rifiuti",
        "telefono": "800473165",
        "email": "clienti@teaspa.it",
        "pec": "mantovaambiente@pec.teaspa.it",
        "note": "Informazioni rifiuti, ambiente, prenotazione ritiro ingombranti domestici. Orario indicato: lunedi-venerdi 8:00-18:00, sabato 9:00-13:00.",
        "tags": ["rifiuti", "ambiente", "ingombranti", "tea", "mantova ambiente"],
        "fonte": "Mantova Ambiente / Tea",
    },
    {
        "id": "mantova-ambiente-centro-raccolta-pegognaga",
        "nome": "Mantova Ambiente - Centro di raccolta Pegognaga",
        "categoria": "Ambiente e rifiuti",
        "telefono": "800473165",
        "indirizzo": "Strada Chiaviche, 84 - Pegognaga (MN)",
        "note": "Centro di raccolta comunale. Verificare orari aggiornati sul sito Mantova Ambiente.",
        "tags": ["centro raccolta", "rifiuti", "pegognaga", "ambiente"],
        "fonte": "Mantova Ambiente - Comune di Pegognaga",
    },
    {
        "id": "antica-farmacia-mori",
        "nome": "Antica Farmacia Mori",
        "categoria": "Farmacia",
        "telefono": "0376559882",
        "indirizzo": "Piazza Giacomo Matteotti, 8 - 46020 Pegognaga (MN)",
        "note": "Farmacia nel Comune di Pegognaga. Verificare turni aggiornati.",
        "tags": ["farmacia", "sanita", "pegognaga"],
        "fonte": "Comune di Pegognaga - Farmacie",
    },
    {
        "id": "farmacia-mancinelli",
        "nome": "Farmacia Mancinelli",
        "categoria": "Farmacia",
        "telefono": "0376525416",
        "indirizzo": "Via Mantovana, 17 - 46020 Pegognaga (MN)",
        "note": "Farmacia nel Comune di Pegognaga, frazione Polesine. Verificare turni aggiornati.",
        "tags": ["farmacia", "sanita", "polesine", "pegognaga"],
        "fonte": "Comune di Pegognaga / Ordine Farmacisti MN",
    },
]
